language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - release

before_install:
  - export PATH=$PATH:$HOME/gopath/bin

matrix:
  allow_failures:
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: release

script:
 - go test -v
